# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
# Linting and coding style
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"

# cs-fixer
- package-ecosystem: composer
  directory: "/vendor-bin/cs-fixer"
  schedule:
    interval: weekly
    day: saturday
    time: "04:10"
    timezone: Europe/Copenhagen
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"

# openapi-extractor
- package-ecosystem: composer
  directory: "/vendor-bin/openapi-extractor"
  schedule:
    interval: weekly
    day: saturday
    time: "04:20"
    timezone: Europe/Brussels
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
    - "provokateurin"

# psalm
- package-ecosystem: composer
  directory: "/vendor-bin/psalm"
  schedule:
    interval: weekly
    day: saturday
    time: "04:30"
    timezone: Europe/Madrid
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"

# phpunit
- package-ecosystem: composer
  directory: "/vendor-bin/phpunit"
  schedule:
    interval: weekly
    day: saturday
    time: "04:40"
    timezone: Europe/Madrid
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"

# Main master npm
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  # Disable automatic rebasing because without a build CI will likely fail anyway
  rebase-strategy: "disabled"

# Testing master npm
- package-ecosystem: npm
  directory: "/build"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  labels:
    - "3. to review"
    - "feature: dependencies"

# Testing master composer
- package-ecosystem: composer
  directory: "/build/integration"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  labels:
    - "3. to review"
    - "feature: dependencies"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  target-branch: stable29
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Disable automatic rebasing because without a build CI will likely fail anyway
  rebase-strategy: "disabled"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  target-branch: stable30
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Disable automatic rebasing because without a build CI will likely fail anyway
  rebase-strategy: "disabled"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 20
  target-branch: stable31
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  # Disable automatic rebasing because without a build CI will likely fail anyway
  rebase-strategy: "disabled"

- package-ecosystem: composer
  directory: "/build/integration"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable29
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

- package-ecosystem: composer
  directory: "/build/integration"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable30
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

- package-ecosystem: composer
  directory: "/build/integration"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  target-branch: stable31
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"
  ignore:
    # ignore all GitHub linguist patch updates
    - dependency-name: "*"
      update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

# GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    timezone: Europe/Paris
  groups:
    github-actions:
      patterns:
        - "*"
  labels:
    - "3. to review"
    - "feature: dependencies"
  reviewers:
    - "nextcloud/server-dependabot"

