# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/nextcloud/pre-commit-php.git
  rev: 1.5.1
  hooks:
  - id: php-lint
  - id: php-cs-fixer
    files: \.(php)$
    exclude: ^(config|data|composer)
    args: []
