sudo: false
language: php
php:
  - 5.4

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

script:
  - sh -c "if [ '$TC' = 'syntax' ]; then composer install && vendor/bin/parallel-lint --exclude vendor/jakub-onderka/ --exclude 3rdparty/patchwork/utf8/class/Patchwork/Utf8/Bootup/ .; fi"

matrix:
  include:
    - php: 5.4
      env: DB=sqlite;TC=syntax
    - php: 5.5
      env: DB=sqlite;TC=syntax
    - php: 5.6
      env: DB=sqlite;TC=syntax

  fast_finish: true
