blank_issues_enabled: false
contact_links:
    - name: â“ Question
      url: https://help.nextcloud.com/
      about: I have a question â€¦
    - name: ğŸ”’ Security Vulnerability
      url: https://hackerone.com/nextcloud
      about: Found a security vulnerability?
