name: Pull request fixup commit check
on: pull_request

jobs:
  commit-message-check:
    name: Block fixup and squash commits
    runs-on: ubuntu-latest
    steps:
      - name: Run check
        uses: xt0rted/block-autosquash-commits-action@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
