name: PHPUnit

on: pull_request

permissions:
  contents: read

concurrency:
  group: phpunit-oci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-oci:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-versions: [ '7.4', '8.0', '8.1']

    services:
      oracle:
        image: deepdiver/docker-oracle-xe-11g # 'wnameless/oracle-xe-11g-r2'
        ports:
          - 1521:1521/tcp

    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, curl, dom, fileinfo, gd, imagick, intl, json, mbstring, oci8, openssl, pdo_sqlite, posix, sqlite, xml, zip
          tools: phpunit:9
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Nextcloud
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=oci --database-name=XE --database-host=127.0.0.1 --database-port=1521 --database-user=autotest --database-pass=owncloud --admin-user admin --admin-pass admin
          php -f index.php

      - name: PHPUnit
        working-directory: tests
        run: phpunit --configuration phpunit-autotest.xml --group DB,SLOWDB

      - name: Run repair steps
        run: |
          ./occ maintenance:repair --include-expensive

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: phpunit-oci

    if: always()

    name: phpunit-oci-summary

    steps:
      - name: Summary status
        run: if ${{ needs.phpunit-oci.result != 'success' }}; then exit 1; fi
