name: PHPUnit custom

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

jobs:
  phpunit-custom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true
          path: server

      - name: Install dependencies
        run: |
          sudo sed -i -e "s/\# deb-src/deb-src/g" /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get build-dep php php-ldap php-zip php-curl php-mbstsring php-intl php-gd php-imagick

      - name: Checkout php
        run: git clone --depth=1 https://github.com/php/php-src.git

      - name: Build php
        working-directory: php-src
        run: |
          ./buildconf
          ./configure --with-ldap --with-ldap-sasl --with-zip --with-curl --with-openssl --with-zlib --enable-mbstring --enable-pcntl --enable-intl --with-password-argon2 --with-freetype --with-jpeg --enable-gd --with-imagick
          #make

      - name: composer i
        working-directory: server
        run: |
          composer i
          composer require --dev phpunit/phpunit

      - name: PHPUnit
        working-directory: server
        run: PATH=../php-src/sapi/cli:$PATH ./autotest.sh sqlite
