# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: PHPUnit 32bits

on:
  pull_request:
    paths:
      - "version.php"
      - ".github/workflows/phpunit-32bits.yml"
      - "tests/phpunit-autotest.xml"
      - "lib/private/Snowflake/*"
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * 1-6"

permissions:
  contents: read

concurrency:
  group: phpunit-32bits-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-32bits:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.4"]

    steps:
      - name: Checkout server
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          submodules: true

      - name: Install dependencies
        uses: docker://ghcr.io/nextcloud/continuous-integration-php8.4-32bit:latest
        with:
          args: /bin/sh -c "
            git config --global --add safe.directory /github/workspace &&
            composer install --no-interaction --prefer-dist
          "

      - name: Set up Nextcloud (SQLite in tmpfs)
        uses: docker://ghcr.io/nextcloud/continuous-integration-php8.4-32bit:latest
        with:
          args: /bin/sh -c "
            set -e

            echo '>> Preparing tmpfs SQLite database'
            mkdir -p /dev/shm/nc-db data
            export SQLITE_TMPDIR=/dev/shm

            echo '>> Installing Nextcloud'
            ./occ maintenance:install \
              --verbose \
              --database=sqlite \
              --database-name=/dev/shm/nc-db/nextcloud.db \
              --database-user=autotest \
              --database-pass=rootpassword \
              --admin-user=admin \
              --admin-pass=admin

            echo '>> Disable SQLite WAL for stability'
            php -r \"
              \$db = new PDO('sqlite:/dev/shm/nc-db/nextcloud.db');
              \$db->exec('PRAGMA journal_mode=DELETE;');
            \"

            echo '>> Enabling all test apps'
            php -f tests/enable_all.php
          "

      - name: PHPUnit
        uses: docker://ghcr.io/nextcloud/continuous-integration-php8.4-32bit:latest
        with:
          args: /bin/sh -c "
            composer run test -- \
              --exclude-group PRIMARY-azure \
              --exclude-group PRIMARY-s3 \
              --exclude-group PRIMARY-swift \
              --exclude-group Memcached \
              --exclude-group Redis \
              --exclude-group RoutingWeirdness
          "
