name: PHPUnit 32bits

on:
  pull_request:
    paths:
      - 'version.php'
      - '.github/workflows/phpunit-32bits.yml'
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * 1-6"

permissions:
  contents: read

concurrency:
  group: phpunit-32bits-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  phpunit-32bits:
    runs-on: ubuntu-latest

    if: ${{ github.repository_owner != 'nextcloud-gmbh' }}

    container: shivammathur/node:latest-i386

    strategy:
      matrix:
        php-versions: ['8.0']

    steps:
      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick libmagickcore-6.q16-3-extra

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d #v2.25.2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ctype, curl, dom, fileinfo, gd, imagick, intl, json, mbstring, openssl, pdo_sqlite, posix, sqlite, xml, zip, apcu
          tools: phpunit:9
          coverage: none
          ini-values:
            apc.enabled=on,
            apc.enable_cli=on
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=autotest --database-pass=rootpassword --admin-user admin --admin-pass admin
          php -f index.php

      - name: PHPUnit
        working-directory: tests
        run: phpunit --configuration phpunit-autotest.xml --exclude-group PRIMARY-azure,PRIMARY-s3,PRIMARY-swift,Memcached,Redis,RoutingWeirdness
