name: Psalm show github

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          submodules: true

      - name: Set up php
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # master
        with:
          php-version: '8.0'
          extensions: ctype,curl,dom,fileinfo,gd,intl,json,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        run: composer i

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions:4.9.3
        continue-on-error: true
        with:
          composer_ignore_platform_reqs: false
          report_file: results.sarif
      - name: Upload Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@231aa2c8a89117b126725a0e11897209b7118144 # v1.1.39
        with:
          sarif_file: results.sarif
